services:
  frontend:
    build:
      context: BooksFront
      dockerfile: Dockerfile
    container_name: books-frontend
  backend:
    build:
      context: BooksBackend
      dockerfile: Dockerfile
    container_name: books-backend
    ports:
      - 4000:4000
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: books-reverse-proxy
    depends_on:
      - frontend
      - backend
