services:
  frontend:
    image: todo-front
    build:
      context: .
      dockerfile: ./todo-frontend/Dockerfile
    ports:
      - 3003:3000
      - 3004:80
    container_name: todo-frontend
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data
  server:
    image: todo-server
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    volumes:
      - ./todo-backend:/usr/src/app
    ports:
      - 3005:3000
    build:
      context: .
      dockerfile: ./todo-backend/Dockerfile
    depends_on:
      - mongo
      - redis
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-reverse-proxy
    depends_on: 
      - frontend
      - server
        
